In [57]:
import pandas as pd
import numpy as np

In [58]:
filename = "relabelledTrimmed1"

In [59]:
df = pd.read_csv('../DataFile/' + filename + '.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df = df.reset_index()
df.drop(columns=['index'], inplace=True)
display(df)

       level_0  accX  accY  accZ                timestamp      Norm  label
0            0 -0.01  0.98 -0.04  2024-03-22 15:39:38.807  0.980867      0
1            1 -0.02  0.99 -0.04  2024-03-22 15:39:38.842  0.991010      0
2            2 -0.01  1.01 -0.04  2024-03-22 15:39:38.843  1.010841      0
3            3  0.00  1.02 -0.03  2024-03-22 15:39:38.844  1.020441      0
4            4  0.02  1.06 -0.03  2024-03-22 15:39:38.882  1.060613      0
...        ...   ...   ...   ...                      ...       ...    ...
75145    75145  0.85 -0.38  0.23  2024-03-22 15:59:02.460  0.959062      0
75146    75146  0.89 -0.37  0.25  2024-03-22 15:59:02.505  0.995741      0
75147    75147  0.93 -0.36  0.25  2024-03-22 15:59:02.509  1.028105      0
75148    75148  0.98 -0.36  0.23  2024-03-22 15:59:02.513  1.069065      0
75149    75149  1.00 -0.27  0.21  2024-03-22 15:59:02.544  1.056882      0

[75150 rows x 7 columns]

In [60]:
# # 1
# df['label'][9702:9777].replace(1,0, inplace=True)
# # 1
# df['label'][9800:9823].replace(1,0, inplace=True)
# # 2
# df['label'][21100:21140].replace(1,0, inplace=True)
# # 3
# df['label'][22115:22138].replace(1,0, inplace=True)
# # 4
# df['label'][23360:23400].replace(1,0, inplace=True)
# # 6
# df['label'][25256:25290].replace(1,0, inplace=True)
# # 8
# df['label'][27205:27226].replace(1,0, inplace=True)
# # 9
# df['label'][28181:28200].replace(1,0, inplace=True)
# # 10
# df['label'][28994:29010].replace(1,0, inplace=True)

df['label'][58768:58769].replace(1,0, inplace=True)

df['label'][60688:60705].replace(1,0, inplace=True)

df['label'][63602:63620].replace(1,0, inplace=True)

df['label'][58775:58868].replace(1,0, inplace=True)

df['label'][59346:59351].replace(1,0, inplace=True)
df['label'][59385:59407].replace(1,0, inplace=True)

In [61]:
import os

os.chdir("../DataFile/")
print(os.getcwd())

count = 0
for path in os.scandir(os.getcwd()):
    if path.is_file() and path.name.endswith('.csv'):
        if 'relabelledTrimmed' in path.name:
            count+=1
count+=1
newPath = '../DataFile/relabelledTrimmed' + str(count) + '.csv'
df.to_csv(newPath)

d:\[01] Laptop Files\[02] GitFolder\mlFallingDetection\DataFile