In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,log_loss

In [13]:
filename = "FallDataExport3"

In [14]:
windowFrame = 10
df = pd.read_csv('../DataFile/' + filename + '.csv')
df.drop(columns=['Unnamed: 0','timestamp', 'accX', 'accY', 'accZ'],inplace=True)
display(df)

col = ["Bias"]
col += (["col"+str(x) for x in range(windowFrame)])
col.append("label")
print(col)

newDict = []
dataPos, itrIndex, tempSum = 0, 0, 0
while dataPos+10 < len(df):
    labelCount = 0
    tempDict = {}
    dataPos = 10+5*itrIndex
    tempDf = df.iloc[0+5*itrIndex:dataPos]
    tempDict = {col[i+1]: tempDf.iloc[i, 0] for i in range(windowFrame)}
    tempDict["Bias"] = 1
    tempSum = tempDf.iloc[:, 1].sum()
    if tempSum >= 5:
        tempDict[col[-1]] = 1
    else:
        tempDict[col[-1]] = 0
    newDict.append(tempDict)
    itrIndex += 1
newDf = pd.DataFrame(newDict, columns=col)
display(newDf)

            Norm   microsecond  label
0       1.013607  4.533665e+14      0
1       1.013361  4.533665e+14      0
2       1.013607  4.533665e+14      0
3       1.013607  4.533665e+14      0
4       1.013607  4.533665e+14      0
...          ...           ...    ...
269032  1.021225           NaN      0
269033  1.021225           NaN      0
269034  1.011237           NaN      0
269035  1.011237           NaN      0
269036  1.020833           NaN      0

[269037 rows x 3 columns]

['Bias', 'col0', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'label']

,Bias,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,label
0,1,1.013607,1.013361,1.013607,1.013607,1.013607,1.013607,1.013361,1.013361,1.013607,1.023572,1
1,1,1.013607,1.013361,1.013361,1.013607,1.023572,1.013361,1.023328,1.013607,1.013607,1.013361,1
2,1,1.013361,1.023328,1.013607,1.013607,1.013361,1.013607,1.023328,1.013607,1.013607,1.013607,1
3,1,1.013607,1.023328,1.013607,1.013607,1.013607,1.023572,1.013607,1.013607,1.013607,1.013607,1
4,1,1.023572,1.013607,1.013607,1.013607,1.013607,1.013361,1.013607,1.013607,1.013361,1.013607,1
...,...,...,...,...,...,...,...,...,...,...,...,...
53800,1,1.011237,1.021225,1.011237,1.011237,1.021225,1.011237,1.011237,1.011237,1.011237,1.021225,0
53801,1,1.011237,1.011237,1.011237,1.011237,1.021225,1.011237,1.021274,1.021225,1.021225,1.021225,0
53802,1,1.011237,1.021274,1.021225,1.021225,1.021225,1.011237,1.021225,1.011286,1.010841,1.011237,0
53803,1,1.011237,1.021225,1.011286,1.010841,1.011237,1.010792,1.011237,1.011237,1.011237,1.021225,0
53804,1,1.010792,1.011237,1.011237,1.011237,1.021225,1.011237,1.010792,1.011237,1.011237,1.011237,0

In [15]:
X = newDf[col[:-1]].to_numpy()
Y = newDf['label'].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=42)
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
loss = log_loss(y_test, y_pred)

# Print the results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6909496376138264
Confusion Matrix:
 [[   0 1663]
 [   0 3718]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00      1663
           1       0.69      1.00      0.82      3718

    accuracy                           0.69      5381
   macro avg       0.35      0.50      0.41      5381
weighted avg       0.48      0.69      0.56      5381

c:\Users\sweea\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sweea\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sweea\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [16]:
logistic_model.coef_

array([[ 3.42888403e-01, -1.18789339e-02,  4.70345594e-02,
         8.88293080e-03,  1.60309768e-02, -6.44021344e-03,
        -5.38109305e-03,  6.85499359e-02,  4.06459099e-03,
         2.56935482e-04, -4.35039496e-04]])